// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnitOfWorkPattern.Context;

#nullable disable

namespace UnitOfWorkPattern.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240707102931_InItDb_V2")]
    partial class InItDb_V2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UnitOfWorkPattern.Models.Entities.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisplayToClient")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentConditionId")
                        .HasColumnType("int");

                    b.Property<string>("TagName")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Title_En")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("nvarchar(155)");

                    b.Property<string>("Title_Jp")
                        .HasMaxLength(155)
                        .HasColumnType("nvarchar(155)");

                    b.HasKey("Id");

                    b.HasIndex("ParentConditionId");

                    b.ToTable("Conditions", "Condition");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6373),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            TagName = "lbl",
                            Title_En = "RUNNING STATUS"
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6385),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            TagName = "lbl",
                            Title_En = "IN/OUT CONDITION"
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6387),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            TagName = "lbl",
                            Title_En = "ACCIDENT"
                        },
                        new
                        {
                            Id = 4,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6391),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            TagName = "lbl",
                            Title_En = "LOADABILITY"
                        },
                        new
                        {
                            Id = 5,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6393),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 1,
                            TagName = "lbl",
                            Title_En = "IS SELF-PROPELLED"
                        },
                        new
                        {
                            Id = 6,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6395),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 5,
                            TagName = "rdb",
                            Title_En = "SELF-PROPELLED"
                        },
                        new
                        {
                            Id = 7,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6397),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 5,
                            TagName = "rdb",
                            Title_En = "NOT SELF-PROPELLED"
                        },
                        new
                        {
                            Id = 8,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6399),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 1,
                            TagName = "lbl",
                            Title_En = "IS DRIVEABLE?"
                        },
                        new
                        {
                            Id = 9,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6401),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 8,
                            TagName = "chk",
                            Title_En = "DRIVABLE"
                        },
                        new
                        {
                            Id = 10,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6403),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 8,
                            TagName = "chk",
                            Title_En = "NOT DRIVABLE"
                        },
                        new
                        {
                            Id = 11,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6405),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 1,
                            TagName = "chk",
                            Title_En = "ENGINE STATUS"
                        },
                        new
                        {
                            Id = 12,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6407),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 9,
                            TagName = "chk",
                            Title_En = "IN GOOD Condition"
                        },
                        new
                        {
                            Id = 13,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6409),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 9,
                            TagName = "chk",
                            Title_En = "STRANGE NOISE"
                        },
                        new
                        {
                            Id = 14,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6411),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 9,
                            TagName = "chk",
                            Title_En = "WHITE SMOKE"
                        },
                        new
                        {
                            Id = 15,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6413),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 9,
                            TagName = "chk",
                            Title_En = "ON BATTRY"
                        },
                        new
                        {
                            Id = 16,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6415),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 9,
                            TagName = "chk",
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 17,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6417),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 1,
                            TagName = "sl",
                            Title_En = "TRANSMISSION"
                        },
                        new
                        {
                            Id = 18,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6420),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 17,
                            Title_En = "IN GOOD ConditionN"
                        },
                        new
                        {
                            Id = 19,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6421),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 17,
                            Title_En = "MALFUNCTION"
                        },
                        new
                        {
                            Id = 20,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6423),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 17,
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 21,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6425),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 1,
                            TagName = "sl",
                            Title_En = "IS CHECK LAMPS LIT"
                        },
                        new
                        {
                            Id = 22,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6427),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 21,
                            Title_En = "YES"
                        },
                        new
                        {
                            Id = 23,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6429),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 21,
                            Title_En = "NO"
                        },
                        new
                        {
                            Id = 24,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6470),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 21,
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 25,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6472),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 2,
                            TagName = "lbl",
                            Title_En = "INTERIOR"
                        },
                        new
                        {
                            Id = 26,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6474),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 25,
                            TagName = "sl",
                            Title_En = "DIRT/STAINS"
                        },
                        new
                        {
                            Id = 27,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6476),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 26,
                            Title_En = "YES"
                        },
                        new
                        {
                            Id = 28,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6478),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 26,
                            Title_En = "NO"
                        },
                        new
                        {
                            Id = 29,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6480),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 26,
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 30,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6482),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 25,
                            TagName = "sl",
                            Title_En = "TEARS IN SEAT"
                        },
                        new
                        {
                            Id = 31,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6484),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 30,
                            Title_En = "YES"
                        },
                        new
                        {
                            Id = 32,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6486),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 30,
                            Title_En = "NO"
                        },
                        new
                        {
                            Id = 33,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6489),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 30,
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 34,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6491),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 25,
                            TagName = "sl",
                            Title_En = "AIR CONDITIONING"
                        },
                        new
                        {
                            Id = 35,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6493),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 34,
                            Title_En = "GOOD"
                        },
                        new
                        {
                            Id = 36,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6495),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 34,
                            Title_En = "BAD"
                        },
                        new
                        {
                            Id = 37,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6497),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 34,
                            Title_En = "NOT CONFIRMED"
                        },
                        new
                        {
                            Id = 38,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6499),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 2,
                            TagName = "ldl",
                            Title_En = "EXTERIOR"
                        },
                        new
                        {
                            Id = 39,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6501),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 38,
                            TagName = "sl",
                            Title_En = "SCRATCHES"
                        },
                        new
                        {
                            Id = 40,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6503),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 39,
                            Title_En = "YES"
                        },
                        new
                        {
                            Id = 41,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6505),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 39,
                            Title_En = "NO"
                        },
                        new
                        {
                            Id = 42,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6507),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 39,
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 43,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6508),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 38,
                            TagName = "sl",
                            Title_En = "DENT"
                        },
                        new
                        {
                            Id = 44,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6510),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 43,
                            Title_En = "YES"
                        },
                        new
                        {
                            Id = 45,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6512),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 43,
                            Title_En = "NO"
                        },
                        new
                        {
                            Id = 46,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6514),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 43,
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 47,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6516),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 38,
                            TagName = "sl",
                            Title_En = "PAINT PEELING"
                        },
                        new
                        {
                            Id = 48,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6519),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 47,
                            Title_En = "YES"
                        },
                        new
                        {
                            Id = 49,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6521),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 47,
                            Title_En = "NO"
                        },
                        new
                        {
                            Id = 50,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6523),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 47,
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 51,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6525),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 35,
                            TagName = "sl",
                            Title_En = "RUST"
                        },
                        new
                        {
                            Id = 52,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6526),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 51,
                            Title_En = "YES"
                        },
                        new
                        {
                            Id = 53,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6529),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 51,
                            Title_En = "NO"
                        },
                        new
                        {
                            Id = 54,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6531),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 51,
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 55,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6533),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 4,
                            TagName = "chb",
                            Title_En = "ENOUGH SPACE"
                        },
                        new
                        {
                            Id = 56,
                            CreatedTime = new DateTime(2024, 7, 7, 13, 59, 29, 190, DateTimeKind.Local).AddTicks(6534),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 4,
                            TagName = "chb",
                            Title_En = "ONLY 2 TON TRUCKS"
                        });
                });

            modelBuilder.Entity("UnitOfWorkPattern.Models.Entities.Condition", b =>
                {
                    b.HasOne("UnitOfWorkPattern.Models.Entities.Condition", "ParentCondition")
                        .WithMany("ChildCondition")
                        .HasForeignKey("ParentConditionId");

                    b.Navigation("ParentCondition");
                });

            modelBuilder.Entity("UnitOfWorkPattern.Models.Entities.Condition", b =>
                {
                    b.Navigation("ChildCondition");
                });
#pragma warning restore 612, 618
        }
    }
}
