// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnitOfWorkPattern.Context;

#nullable disable

namespace UnitOfWorkPattern.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240707145754_InItDb_V5")]
    partial class InItDb_V5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UnitOfWorkPattern.Models.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisplayToClient")
                        .HasColumnType("bit");

                    b.Property<string>("MakerName")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearOfMade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars", "Vehicle");
                });

            modelBuilder.Entity("UnitOfWorkPattern.Models.Entities.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisplayToClient")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentConditionId")
                        .HasColumnType("int");

                    b.Property<string>("TagName")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Title_En")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("nvarchar(155)");

                    b.Property<string>("Title_Jp")
                        .HasMaxLength(155)
                        .HasColumnType("nvarchar(155)");

                    b.HasKey("Id");

                    b.HasIndex("ParentConditionId");

                    b.ToTable("Conditions", "Condition");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2289),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            TagName = "lbl",
                            Title_En = "RUNNING STATUS"
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2299),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            TagName = "lbl",
                            Title_En = "IN/OUT CONDITION"
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2300),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            TagName = "lbl",
                            Title_En = "ACCIDENT"
                        },
                        new
                        {
                            Id = 4,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2302),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            TagName = "lbl",
                            Title_En = "LOADABILITY"
                        },
                        new
                        {
                            Id = 5,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2304),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 1,
                            TagName = "lbl",
                            Title_En = "IS SELF-PROPELLED"
                        },
                        new
                        {
                            Id = 6,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2306),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 5,
                            TagName = "rdb",
                            Title_En = "SELF-PROPELLED"
                        },
                        new
                        {
                            Id = 7,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2308),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 5,
                            TagName = "rdb",
                            Title_En = "NOT SELF-PROPELLED"
                        },
                        new
                        {
                            Id = 8,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2310),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 1,
                            TagName = "lbl",
                            Title_En = "IS DRIVEABLE?"
                        },
                        new
                        {
                            Id = 9,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2312),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 8,
                            TagName = "chk",
                            Title_En = "DRIVABLE"
                        },
                        new
                        {
                            Id = 10,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2314),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 8,
                            TagName = "chk",
                            Title_En = "NOT DRIVABLE"
                        },
                        new
                        {
                            Id = 11,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2316),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 1,
                            TagName = "chk",
                            Title_En = "ENGINE STATUS"
                        },
                        new
                        {
                            Id = 12,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2318),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 9,
                            TagName = "chk",
                            Title_En = "IN GOOD Condition"
                        },
                        new
                        {
                            Id = 13,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2320),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 9,
                            TagName = "chk",
                            Title_En = "STRANGE NOISE"
                        },
                        new
                        {
                            Id = 14,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2322),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 9,
                            TagName = "chk",
                            Title_En = "WHITE SMOKE"
                        },
                        new
                        {
                            Id = 15,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2324),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 9,
                            TagName = "chk",
                            Title_En = "ON BATTRY"
                        },
                        new
                        {
                            Id = 16,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2326),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 9,
                            TagName = "chk",
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 17,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2328),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 1,
                            TagName = "sl",
                            Title_En = "TRANSMISSION"
                        },
                        new
                        {
                            Id = 18,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2330),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 17,
                            Title_En = "IN GOOD ConditionN"
                        },
                        new
                        {
                            Id = 19,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2332),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 17,
                            Title_En = "MALFUNCTION"
                        },
                        new
                        {
                            Id = 20,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2334),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 17,
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 21,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2336),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 1,
                            TagName = "sl",
                            Title_En = "IS CHECK LAMPS LIT"
                        },
                        new
                        {
                            Id = 22,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2338),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 21,
                            Title_En = "YES"
                        },
                        new
                        {
                            Id = 23,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2340),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 21,
                            Title_En = "NO"
                        },
                        new
                        {
                            Id = 24,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2342),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 21,
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 25,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2344),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 2,
                            TagName = "lbl",
                            Title_En = "INTERIOR"
                        },
                        new
                        {
                            Id = 26,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2346),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 25,
                            TagName = "sl",
                            Title_En = "DIRT/STAINS"
                        },
                        new
                        {
                            Id = 27,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2348),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 26,
                            Title_En = "YES"
                        },
                        new
                        {
                            Id = 28,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2350),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 26,
                            Title_En = "NO"
                        },
                        new
                        {
                            Id = 29,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2352),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 26,
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 30,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2354),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 25,
                            TagName = "sl",
                            Title_En = "TEARS IN SEAT"
                        },
                        new
                        {
                            Id = 31,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2356),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 30,
                            Title_En = "YES"
                        },
                        new
                        {
                            Id = 32,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2358),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 30,
                            Title_En = "NO"
                        },
                        new
                        {
                            Id = 33,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2360),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 30,
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 34,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2362),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 25,
                            TagName = "sl",
                            Title_En = "AIR CONDITIONING"
                        },
                        new
                        {
                            Id = 35,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2364),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 34,
                            Title_En = "GOOD"
                        },
                        new
                        {
                            Id = 36,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2366),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 34,
                            Title_En = "BAD"
                        },
                        new
                        {
                            Id = 37,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2368),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 34,
                            Title_En = "NOT CONFIRMED"
                        },
                        new
                        {
                            Id = 38,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2370),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 2,
                            TagName = "ldl",
                            Title_En = "EXTERIOR"
                        },
                        new
                        {
                            Id = 39,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2372),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 38,
                            TagName = "sl",
                            Title_En = "SCRATCHES"
                        },
                        new
                        {
                            Id = 40,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2373),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 39,
                            Title_En = "YES"
                        },
                        new
                        {
                            Id = 41,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2375),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 39,
                            Title_En = "NO"
                        },
                        new
                        {
                            Id = 42,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2377),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 39,
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 43,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2380),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 38,
                            TagName = "sl",
                            Title_En = "DENT"
                        },
                        new
                        {
                            Id = 44,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2382),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 43,
                            Title_En = "YES"
                        },
                        new
                        {
                            Id = 45,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2384),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 43,
                            Title_En = "NO"
                        },
                        new
                        {
                            Id = 46,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2386),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 43,
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 47,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2388),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 38,
                            TagName = "sl",
                            Title_En = "PAINT PEELING"
                        },
                        new
                        {
                            Id = 48,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2390),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 47,
                            Title_En = "YES"
                        },
                        new
                        {
                            Id = 49,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2391),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 47,
                            Title_En = "NO"
                        },
                        new
                        {
                            Id = 50,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2393),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 47,
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 51,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2395),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 35,
                            TagName = "sl",
                            Title_En = "RUST"
                        },
                        new
                        {
                            Id = 52,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2397),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 51,
                            Title_En = "YES"
                        },
                        new
                        {
                            Id = 53,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2399),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 51,
                            Title_En = "NO"
                        },
                        new
                        {
                            Id = 54,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2401),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 51,
                            Title_En = "UNCONFIRMED"
                        },
                        new
                        {
                            Id = 55,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2403),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 4,
                            TagName = "chb",
                            Title_En = "ENOUGH SPACE"
                        },
                        new
                        {
                            Id = 56,
                            CreatedTime = new DateTime(2024, 7, 7, 18, 27, 54, 54, DateTimeKind.Local).AddTicks(2405),
                            IsDeleted = false,
                            IsDisplayToClient = true,
                            ParentConditionId = 4,
                            TagName = "chb",
                            Title_En = "ONLY 2 TON TRUCKS"
                        });
                });

            modelBuilder.Entity("UnitOfWorkPattern.Models.Entities.Condition", b =>
                {
                    b.HasOne("UnitOfWorkPattern.Models.Entities.Condition", "ParentCondition")
                        .WithMany("ChildCondition")
                        .HasForeignKey("ParentConditionId");

                    b.Navigation("ParentCondition");
                });

            modelBuilder.Entity("UnitOfWorkPattern.Models.Entities.Condition", b =>
                {
                    b.Navigation("ChildCondition");
                });
#pragma warning restore 612, 618
        }
    }
}
